name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 150

      - name: Install and run Luacheck
        uses: nebularg/actions-luacheck@v1
        with:
          args: '--no-color -qo "011"'
          annotate: warning
